### ISSUE TITLE
代码运行在一维卷积报错。

### ISSUE THREAD

**Issue by YINhang23** [Ziqiang-Liu/GraphCDD#1]
作者你好，我再运行你的代码的时候，在进行一维卷积的时候，报错，说输入的shape不对，这是为什么呢？
希望您能回答，十分感谢。

**Comment by Ziqiang-Liu** [comment]
如果你使用的是我提供的数据的话，我并没遇到这个错误。可以查看自己的环境版本和参数设置，是否与代码一致。

**Comment by ProZhang-Gr** [comment]
同样的问题，我也不敢乱改代码呜呜呜

**Comment by ProZhang-Gr** [comment]
请问您最后复现了嘛，方便看一下代码嘛

**Comment by ProZhang-Gr** [comment]
可能是环境问题，不过在配置环境的时候，发现已经没有匹配最新显卡（12.0以上）的作者指定pytorch了
